#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-pkgload
Version  : 1.0.2
Release  : 6
URL      : https://cran.r-project.org/src/contrib/pkgload_1.0.2.tar.gz
Source0  : https://cran.r-project.org/src/contrib/pkgload_1.0.2.tar.gz
Summary  : Simulate Package Installation and Attach
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ GPL-3.0
Requires: R-pkgload-lib = %{version}-%{release}
Requires: R-desc
Requires: R-pkgbuild
Requires: R-rlang
Requires: R-rstudioapi
Requires: R-withr
BuildRequires : R-desc
BuildRequires : R-pkgbuild
BuildRequires : R-rlang
BuildRequires : R-rstudioapi
BuildRequires : R-withr
BuildRequires : buildreq-R

%description
and then attaching it. This is a key part of the 'devtools' package as it
    allows you to rapidly iterate while developing a package.

%package lib
Summary: lib components for the R-pkgload package.
Group: Libraries

%description lib
lib components for the R-pkgload package.


%prep
%setup -q -c -n pkgload

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540852808

%install
export SOURCE_DATE_EPOCH=1540852808
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgload
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgload
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library pkgload
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library pkgload|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/pkgload/DESCRIPTION
/usr/lib64/R/library/pkgload/INDEX
/usr/lib64/R/library/pkgload/Meta/Rd.rds
/usr/lib64/R/library/pkgload/Meta/features.rds
/usr/lib64/R/library/pkgload/Meta/hsearch.rds
/usr/lib64/R/library/pkgload/Meta/links.rds
/usr/lib64/R/library/pkgload/Meta/nsInfo.rds
/usr/lib64/R/library/pkgload/Meta/package.rds
/usr/lib64/R/library/pkgload/NAMESPACE
/usr/lib64/R/library/pkgload/NEWS.md
/usr/lib64/R/library/pkgload/R/pkgload
/usr/lib64/R/library/pkgload/R/pkgload.rdb
/usr/lib64/R/library/pkgload/R/pkgload.rdx
/usr/lib64/R/library/pkgload/WORDLIST
/usr/lib64/R/library/pkgload/help/AnIndex
/usr/lib64/R/library/pkgload/help/aliases.rds
/usr/lib64/R/library/pkgload/help/paths.rds
/usr/lib64/R/library/pkgload/help/pkgload.rdb
/usr/lib64/R/library/pkgload/help/pkgload.rdx
/usr/lib64/R/library/pkgload/html/00Index.html
/usr/lib64/R/library/pkgload/html/R.css
/usr/lib64/R/library/pkgload/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/pkgload/libs/pkgload.so
/usr/lib64/R/library/pkgload/libs/pkgload.so.avx2
/usr/lib64/R/library/pkgload/libs/pkgload.so.avx512
